### ISSUE TITLE
Implementing Graph RAG for high level thematic Q&A's

### ISSUE THREAD

**Issue by varun-singhh** [huggingface/huggingface-llama-recipes#49]
This issue is from #43 

Proposing the implementation of a Graph RAG that can:
- Efficiently Scale with the generality of the questions and the size of the text corpus being indexed
- Addressing QFS tasks by combining graph-based document representation methods with RAG's retrieval capabilities, such as improved handling of large-scale datasets with general user queries.

**Comment by ariG23498** [comment]
Hey @varun-singhh 

Thank you for the great proposal, I'm afraid, this falls a bit outside the purview of this repo as our aim is to create minimal, reproducible snippets that developers can use in their existing workflows instead of end to end cookbook style notebooks.

Closing this issue, please feel free to create a new issue with another proposal 🤗
