### ISSUE TITLE
Use COT and "Take a breath" techiniques with RAG for building trusthworthy RAG

### ISSUE THREAD

**Issue by silvererudite** [huggingface/huggingface-llama-recipes#59]
This issue is in response to the, call for contributions https://github.com/huggingface/huggingface-llama-recipes/issues/43.

Hi @ariG23498, I would like to contribute a simple use case of building transparent and trustworthy RAG pipeline with LLama where we can identify which parts of a RAG generated outputs are retrieved and which parts are from llm generated. I already did an implementation yesterday using LLama 8B instruct. Pls have a look at the notebook. https://github.com/silvererudite/generative-ai/blob/main/interpretable_generative_ai/visualize_rag_generated_response.ipynb

Pls let me know if this would align with the parent issue's contributing guidelines or if there's any feedback, suggestion or any conflict of interest. Thanks!

**Comment by ariG23498** [comment]
Hey @silvererudite 

This is a really nice project on its own! Unfortunately we are not looking for something like this for our repository. The `llama-recipes` repo was built in order to house code snippets that are simple for any beginner to start working with the Llama family of models.

This example is a very thorough project which should have its own place. Closing this issue, please feel free to suggest something that aligns with the type of code that already exists in the repository! 🤗
